version: "3.7"

volumes:
    db:
        driver: local

services:
    mariadb:
        image: "mariadb:latest"
        container_name: mariadb
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d:ro,Z

    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app
        restart: on-failure
        env_file:
            - .env
        environment:
            APPLICATION_PORT: 8080
        ports:
            - "8080:8080"
        depends_on:
            - mariadb





