// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "app/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetPricingByDate mocks base method.
func (m *MockStorage) GetPricingByDate(ctx context.Context, data domain.RequestPricing) ([]domain.Pricing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPricingByDate", ctx, data)
	ret0, _ := ret[0].([]domain.Pricing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricingByDate indicates an expected call of GetPricingByDate.
func (mr *MockStorageMockRecorder) GetPricingByDate(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricingByDate", reflect.TypeOf((*MockStorage)(nil).GetPricingByDate), ctx, data)
}
